server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

weixin:
  config:
    originalid: gh_e067c267e057
    token: b8b6
    app-id: wx63ded3b1ebcc8d1f
    app-secret: 60b02843278a87dbafa40b81d5e90ae5
    template_id: hIs44PNrUH9Qd7RUk_vPpksSMGt08LVIqUHjmgsJFQ4

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:13306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml



# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000132689924
  merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCVrUronsYjxLwyrV9L0DUfuURO+6x2DNKcKH5zSKDsLQtRCxsUElxvk25Fwc5z+iDYwBjj+ol9pYXtan+IgjVesaRSnl7H7T/4RfTsncaQxIskm2KlR4dpu729kpalniFfhgOhFz9TgzsFNwqihnK6XrB2hPotY/DG6qWHAbR9pwnDFfFqJy2+roZ/cBHo9oAF68a54jsI6+cMG6/0YMd/WOIkdrAMT59cQlkFCGFnRkko7GMiiOFer46WSUBzYPKhtwMOkPijz3HYCnZ7y8p6gGZTQchyzkxiDRaPdvG0byCOF+wol8kAhiFO5X/fWCayvNJU5uFhqc0ZZhWmqVuHAgMBAAECggEAKyoytCs10RLng2XkWaTN7TwsquqBrfm8szQqY2zKm9HRtamSQZOZ/MNzxcJCm8fCuT+M7hJOnGGj4fgYl3GVmp14Wis6AkY1cJAcNjC6Fv3XctMs+6VJNADkk0s3DsQvs7CeU1K0/IyX9MUO2BgV9hFgqo1m6Lgts+/vlKO1PZb/0y55LrKfULjEfgKZDsH6zjzw5CFDWxnxUDmMvPODGC/DcGazMHCCSMauljkHg7m2HLOxpNicKHikWEueFljDiTsd3gEJo5DUNag8xxRFF0Ad1xuLe+Mv2sUePfV0Kh+rmldydfng+0+95d5FRsbArXROy47YObD7GTq9DmUMAQKBgQDp4qb4v2ZXcyiR3ZLuthCpWukDfK3TIbiURs1Cx6srngzPOczridhDAmZ6vMAyJ+WTeFgrA5XYtRGD5Q3JwErZQOsFvj98Q2NGDPtKyOUBT/9vNZWpBN+vnvLbgGqIVnoQfO+4bQ23mpAjut6yBMc2zd0kMlx8GyE1wgdGvneugQKBgQCj1FH67TwRr2As/vULH+TJt1AksbdreVw5OP7ud9qBOkapNZ6A9X6Hn5NGnt3cLfgr/GgH5LrIEMPZKMDuP3tj2TPrM9WirHUrAEIDPFd6SV61ddvEFv3JRYATP8Kk3L2PJVMn5u7NcMl+EjWSrNaC73rLOzl0KvCNO+BSRySWBwKBgEyq4ocJ3tdtxW/DTUX44o9RYK6m8SgTlrjsWJ66aw7aOWK4lMblIcIdiFBVjT8juurTeTtoandmK36r2BA5e4+p6yCv04m9YU52NO232vHKMnZW/18vXM/p77wqZUGZ71t2SPKQtP1pqjQ8LoH2dQMvCn2yEIUSM5m2p8H176+BAoGATdQp9gkJxmUITZf5lYVbTTDW0/fRaS9ITq7y/RrXJRkoRG6ClEUMDSYT8zK5t0XnZg4M5eMVkMHWKK4hqY1i8vZWoeAIF7XSG9GNirf53tBIO/B3rNo3SozH4V0i/OsY6o4SyRv+Sn7QWiIQbVPKvH1EWpQSIUvc51uQn8XIbbUCgYAFdj1f/d7mphwY9eDyhKlFf8CsUiuX9WHNSFqS8EcCKb6y2uKXeY3wDktwzclPHuiKHXZBTXkZQ6WavHQMgixUwno4gqFsXKgTn5CM28RQpDLeCrjaKHVHZvkCDMSIgZDdQckWrr7fJb4E/2PkuPZmQzOWYiUDFpITM1c88unr2g==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg+44wjdo/WnHGgTf9CjWSEpdWEx1jlF6Sz9R3yc9cpQ3+1SKN9TsZXZs1RpaMcL8vdj569EZ3mfIlSmQP+C2Qe8HoS1TU01bl8SC/Y4GdCZqYGO11cTO/IlW9q8OVsuFRQrwfQVd6A9VZssZPuFa/RMwXiYJB6KPKtzehwDkcyO/25tbHjdMzz5e5yelr6G1S0jc9iit5unGZoDLYP3EDEVHDoCvOes+Wat5wHe+6kqKb8v5pPfyrEjYXdsEMJ4j6+TuwdVaCT7jFJ2GFnjV8LFZ+8bRC7DAAOBpp5C7mmwkRfZU9NOPyjJeR4U0RwlckXVDrGfeKmIH5fte3cEm9wIDAQAB
# 页面跳转异步通知页面路径,需要需要http:// 格式的完整路径,不能加?id=123这类自定义参数,必须外网可以正常访问
  notify_url: http://yzh-mall.natapp1.cc/api/v1/alipay/pay_notify
#  页面跳转同步通知页面路径,需要http:// 格式的完整路径,不能加?id=123这类自定义参数,必须外网可以正常访问
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml